dist: trusty
group: travis_latest
sudo: false
cache:
    directories:
        - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    #- python: "2.7"
    #  env: TOXENV=py27-threads
    - python: "3.6"
      env: TOXENV=py36-threads
    - python: "3.7"
      env: TOXENV=py37-threads
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=py37-greenlets
      dist: xenial
      sudo: true

install:
  - pip install -U tox
  - pip install -e .

script:
  - tox


before_install:
  - "echo 'starting'"
  - "echo $PYTHONPATH"
  - pip install codecov
  - pip install ansi2html # for the bash_run into_file=....html feature
  #- sudo pip install -U attrs structlog nose appdirs funcsigs colorama
  #- sudo python setup.py install


  #sudo coverage run --include="app_conf/__init__.py"  setup.py test
  # those paths seem to be needed if you run tests directly, otherwise libs
  # are not found. strange:
  #echo $PYTHONPATH && export PYTHONPATH="`pwd`:$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages" && python -c "import docopt, markdown, pygments, yaml" && python mdv/tests/test_files.py

  #- "ls -la /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages"
  #- "ls -la /usr/lib/python2.7/dist-packages"
  #- "ls -la /usr/local/lib/python2.7/dist-packages"

after_success:
  - tox -e coverage-report
  - codecov

notifications:
    email: false

