"""
Creates Readme - while testing functions of p2m.


While pytest is running we simply assemble from scratch an intermediate .md file
in append only mode, located within the tests folder.
This we insert between two seperators in the target markdown file, as the last
test function, done.
"""
import pytest2md as p2m
import pytest, json, os, time
from functools import partial
from uuid import uuid4
import json

# a P2M instance contains all we need:
p2m = p2m.P2M(__file__, fn_target_md='README.md')


# parametrizing the shell run results:
run = partial(p2m.bash_run, no_cmd_path=True)


doc_src = partial(
    p2m.md_from_source_code, pre_md='Generated by:', no_sh_func_output=True
)
md = p2m.md


class TestChapter1:
    def test_one(self):
        t = """

        This is a set of tools, *generating* documentation, while verifying the documented
        claims about code behaviour - without the need to adapt the source code, e.g. by modifying
        doc strings:

        ![](./assets/shot1.png)

        > When the documentation is using a lot of code examples then a very welcome
        additional benefit of writing it like shown is the availability of [source
        code autoformatters](https://github.com/ambv/black).

        Other Example:

        This "README.md" was built into [this](./.README.tmpl.md) template,
        where [title:html comment style placeholders,fmatch:.README.tmpl.md,show_raw:True]<SRC>
        had been replaced while running pytest on [test_tutorial](./tests/test_tutorial.py).


        """
        p2m.md(t)
        p2m.md(
            """
        Lets run a bash command and assert on its results.
        Note that the command is shown in the readme, incl. result and the result
        can be asserted upon.
        """
        )

        res = run('cat "/etc/hosts" | grep localhost')
        assert '127.0.0.1' in res[0]['res']

    def test_two(self):
        res = run(['ls "%(d_test)s"' % p2m.ctx, 'ls -lta /etc/hosts'])
        assert 'tutorial' in res[0]['res']
        assert 'hosts' in res[1]['res']

    def test_simple_pyfuncs(self):
        """
        # Inline Python Function Execution

        via the `md_from_source_code` function you can write fluent markdown
        (tested) python combos:
        """

        def foo():
            hi = 'hello world'
            assert 'world' in hi
            print(hi.replace('world', 'joe'))

        """
        The functions are evaluated and documented in the order they show up
        within the textblocks.

        > Please keep tripple apostrophes - we split the text blocks,
        searching for those.

        State is kept within the outer pytest function, like normally in python.
        I.e. if you require new state, then start a new pytest function.

        Stdout is redirected to an output collector function, i.e. if you print
        this does result in an "Output" block. If the printout starts with
        "MARKDOWN:" then we won't wrap that output into fenced code blocks but
        display as is.

        > If the string 'breakpoint' occurs in a function body, we won't redirect
        standardout for displaying output.

        # Features

        ## html_table

        """

        def mdtable():
            ht = p2m.html_table

            print(ht([['foo', 'bar'], ['bar', 'baz']], ['h1', 'h2']))
            print('As details when summary arg is given:')
            t = ht(
                [['joe', 'doe'], ['suzie', 'wong']],
                ['first', 'last'],
                summary='names. click to open...',
            )
            assert 'details' in t
            assert 'joe</td' in t
            print(t)

        doc_src()

    def test_file_create_show(self):
        p2m.md('## sh_file')
        fn = '/tmp/test_file.json'
        ts = time.ctime()
        c = json.dumps({'a': [{'testfile': 'created'}, 'at', ts]}, indent=4)

        def shf():
            # if content is given it will create it:
            p2m.sh_file(fn, lang='javascript', content=c)
            # summary arg creates a details structure:
            p2m.sh_file(fn, lang='javascript', content=c, summary='as details')
            # creates a link (say True to have the filename as link text)
            p2m.sh_file(fn, lang='javascript', content=c, as_link=True)
            p2m.sh_file(fn, lang='javascript', content=c, as_link='as link')

        doc_src()
        # check existance:
        with open(fn) as fd:
            assert fd.read() == c
        os.unlink(fn)

    def test_bash_run(self):
        p2m.md('## bash_run')

        def br():
            run = partial(p2m.bash_run, no_cmd_path=True)
            # by default we search in assets for the command to run:
            res = p2m.bash_run('some_command_in_assets arg1 2>&1')
            assert 'No such file' in res[0]['res']
            res = run('cat /etc/hostname | grep local | head -n 1')
            assert 'local' in res[0]['res']
            res = run('cat /etc/hostname', into_file='bash_run.txt')
            assert 'local' in res[0]['res']
            # Ending with .html it converts ansi escape colors to html:
            # simple link is created.
            # (requires pip install ansi2html)
            run('cat /etc/resolv.conf', into_file='bash_run.html')

        doc_src()

    def test_md_from_source_code(self):
        p2m.md('## md_from_source_code')

        def br():
            def func1():
                p2m.md('Inserted markdown from running python.')
                print('From output of running python ')

            def func2():
                print('From another function')

            p2m.md_from_source_code()

        doc_src()

    def test_toc_making(self):
        p2m.md(
            """
        ## Table of Contents

            p2m.write_markdown(with_source_ref=True, make_toc=True)

        See this tutorial.

        """
        )

    def test_mdtool(self):
        md = """
        # Link Replacements

        Technical markdown content wants to link to source code often.
        How to get those links working and that convenient?

        The module does offer also some source finding / link replacement feature,
        via the [mdtool]<SRC> module. The latter link was built simply by this:

        ```
        [mdtool]<SRC>
        ```


        Other example: This [test_tutorial.py]<SRC> link was created by replacing "SRC" with the path
        to a file matching, under a given directory, prefixed by an arbitrary base URL.

        ## Spec

        These will be replaced:

        `[title:this,fmatch:test_tutorial,lmatch:line_match] <SRC>` (remove space between] and <)

        - title: The link title - text the user reads
        - fmatch: substring match for the link destination file
        - lmatch: Find matching line within that file
        - show_raw: Link to raw version of file, not the one rendered by the
          repo server
        - path: Fix file path (usually derived by fmach)
        - line: Fix the line number of the link (usually done via lmatch)

        ## Code Repo Hoster Specific Source Links

        Github, Gitlab, Bitbucked or Plain directory based static content servers
        all have their conventional URLs regarding those links.

        Since all of these are just serving static content w/o js possibilities,
        you have to parametrize the intended hoster in your environment, before
        running a pytest / push cycle. That way the links will be working on the hoster.

        Currently we understand the following namespaces for links:


        ```javascript
        _link_names_
        ```

        ### Setting a link template

        - `export MD_LINKS_FOR=github   ` # before running pytest / push
        - `<!-- md_links_for: github -->` # in the markdown template, static

        The latter can be overwritten by environ, should you want to push from time to time
        to a different code hoster.

        ### Link Refs

        We minimize the problem of varying generated target markdown, dependent on the hoster.
        How? Like [any problem in IT is solved](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering).


        By building [reference links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)
        the differences of e.g. a README.md for github vs. gitlab is
        restricted to the links section on the end of the generated markdown.
        In the markdown bodies you'll just see link names, which remain the same.

        > Check the end of the [title:rendering result,fmatch:README.md,show_raw:True]<SRC> at the end of this README.md,
        in order to see the results for the hoster you are reading this markdown file currently.

        ## Summary

        - At normal runs of pytest, the link base URL is just a local `file://` link,

        - Before pushes one can set via environ (e.g. `export
          MD_LINKS_FOR=github`)  these e.g. to the github base URL or the repo.

        - `[key-values]` constructs are supported as well, extending to beyond
          just the base url. Example following:

        """.replace(
            '_link_names_',
            json.dumps(p2m.src_link_templates, indent=4, sort_keys=2),
        )
        p2m.md(md)

    def test_sh_code(self):
        p2m.md('Source code showing is done like this:')
        p2m.sh_code(self.test_sh_code)
        p2m.md(
            '> Is [title:this,fmatch:test_tutorial,lmatch:exotic]<SRC> an exotic form of a recursion? ;-)  '
        )

    def test_write(self):
        """has to be the last 'test'"""
        # default is ../README.md
        p2m.write_markdown(with_source_ref=True, make_toc=True)
